const PERMISSIONS = {
  admin: {
    create_report: true,
    create_dispatch: true,
    create_purchase: true,
    view_reports: true,
    view_dispatches: true,
    view_purchases: true,
    view_spare_parts: true,
    create_spare_parts: true,
    export: true,
    manage_users: true,
    plant_settings: true,
    switch_plant: true,
    assign_tasks: true,
  },
  plant_manager: {
    create_report: true,
    create_dispatch: true,
    create_purchase: true,
    view_reports: true,
    view_dispatches: true,
    view_purchases: true,
    view_spare_parts: true,
    create_spare_parts: true,
    export: true,
    manage_users: true,
    plant_settings: true,
    switch_plant: false,
    assign_tasks: true,
  },
  supervisor: {
    create_report: true,
    create_dispatch: true,
    create_purchase: true,
    view_reports: true,
    view_dispatches: true,
    view_purchases: true,
    view_spare_parts: true,
    create_spare_parts: true,
    export: true,
    manage_users: false,
    plant_settings: false,
    switch_plant: false,
    assign_tasks: true,
  },
  purchase_manager: {
    create_report: false,
    create_dispatch: false,
    create_purchase: true,
    view_reports: true,
    view_dispatches: false,
    view_purchases: true,
    view_spare_parts: false,
    create_spare_parts: false,
    export: false,
    manage_users: false,
    plant_settings: false,
    switch_plant: false,
  },
  accountant: {
    create_report: false,
    create_dispatch: false,
    create_purchase: false,
    view_reports: true,
    view_dispatches: true,
    view_purchases: true,
    view_spare_parts: true,
    create_spare_parts: false,
    export: true,
    manage_users: false,
    plant_settings: false,
    switch_plant: false,
  },
}

export function can(role, action) {
  return !!PERMISSIONS[role]?.[action]
}

export const ROLE_OPTIONS = [
  { value: 'admin', label: 'Admin', description: 'Everything + cross-plant access & user management' },
  { value: 'plant_manager', label: 'Plant Manager', description: 'Full access for their plant — all operations, export, manage team' },
  { value: 'supervisor', label: 'Supervisor', description: 'Full plant operations — reports, dispatches, purchases' },
  { value: 'purchase_manager', label: 'Purchase Manager', description: 'Raw material purchases only' },
  { value: 'accountant', label: 'Accountant', description: 'Read-only access + export to CSV/Sheets' },
]
